### ISSUE TITLE
6 Schritte zur ersten Elbfisch-Applikation

### ISSUE THREAD

**Issue by ghost** [mskgmbh/elbfisch#1]
Hi,

ich habe nach der Anleitung Elbfisch bei mir installiert und testweise ausgeführt. 

Hier ein paar Anmerkungen zum Dokument:
- Der erste Link zur jar-Datei "org.jpac.jar" verweist auf "org.jpac.plc.jar". 
- Apache common-logging gibt es erst in der Version 1.1.1, bzw. habe keine aktuellere Version gefunden.

Gruß
Reinhard

**Comment by BerndSchuster** [comment]
Hallo Reinhard, 
ja, du musst zu recht annehmen, dass ich 3 Jahre benötige um dir zu antworten. Ich habe es einfach nicht gesehen, daß du hier einen issue aufgemacht hast. Danke für die Rückmeldung. Ich werde das korrigieren. 
Aber, falls es dich noch interessiert: Elbfisch lebt, ist seither kräftige weiterentwickelt worden. Es gibt jetzt ein "vioss" (Versatile Input Output System), in dem schon "Treiber" für die GPIO vom Raspberry Pi, Beckhoff ADS und einen OPC UA client eingeflossen sind. Weiter für Siemens S7 und Modbus/TCP werden folgen.
Darüberhinaus stellt Elbfisch nun auch einen OPC UA server zur Verfügung.
Dies alles wird in den kommenden Wochen online gestellt.
Also, falls noch Interesse besteht. Viel Freude damit.

Bernd
